numpad=[[0,0,0,0,0,0,0],[0,0,0,1,0,0,0],[0,0,2,3,4,0,0],[0,5,6,7,8,9,0],[0,0,10,11,12,0,0],[0,0,0,13,0,0,0],[0,0,0,0,0,0,0]]
currentx=4
currenty=4
direction="DURRDLLLDDLLDLLRLULULLRDLDRRDDRDLRULURRDUUDDRLLDDLDRRLRDUDRULDLRURDUUDRDDLLDRRDRUDUDULLDDDDLDRRRLRLRDRDLURRDDLDDDUUDRDRLLLDLUDDDLUULRDRLLLRLLUULUDDDRLDUUUURULRDDURRDRLUURLUDRLRLLLDDLRDDUULRRRRURDLDDDRLDLDRRLLDRDDUDDUURDLDUUDRDLDLDDULULUDDLRDDRLRLDDLUDLLDRLUDUDDRULLRLDLLRULRUURDDRDRDRURDRRLRDLLUDDRRDRRLDDULLLDLUDRRUDLDULDRURRDURLURRLDLRDLRUDLULUDDRULRLLDUURULURULURRLURRUULRULRRRLRDLULRLRLUDURDDRUUURDRLLRRRDDLDRRRULLDLRDRULDRRLRRDLUDDRDDDUUURRLULLDRRUULULLRRRRLDDRDDLUURLLUDLLDUDLULUULUDLLUUURRRUDDDRLLLRDRUUDUUURDRULURRLRDLLUURLRDURULDRRUDURRDDLDRLDRUUDRLLUDLRRU"
for i in range(len(direction)):
    if direction[i]=="U":
        if numpad[currenty-1][currentx]!=0:
            currenty-=1
    elif direction[i]=="D":
        if numpad[currenty+1][currentx]!=0:
            currenty+=1
    elif direction[i]=="L":
        if numpad[currenty][currentx-1]!=0:
            currentx-=1
    else: #R
        if numpad[currenty][currentx+1]!=0:
            currentx+=1
print (numpad[currenty][currentx])
print ("current x:",currentx)
print ("current y:",currenty)

        
    
